# Generated by Django 3.2.5 on 2021-07-24 05:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Images', '0002_images_timestamp'),
    ]

    operations = [
        migrations.RenameField(
            model_name='images',
            old_name='image_uri',
            new_name='image',
        ),
    ]
